
name: testing
on: [push]
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python
    - uses: actions/setup-python@v1
      with:
          python-version: '3.9'
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: Run tests
      run: pytest --cov
    - name: Tests report
