
name: testing
on: [push]
jobs:
  run_tests:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v1
      with:
          python-version: '3.9'
    - name: Install requirements
      run: pip install -r requirements.txt
    - name: dir
      run: ls
    - name: Run tests
      run: pytest
    - name: Tests report
      run: coverage report
